import json
import random

# 1. & 2. EXTENSIVE NAME VARIATIONS (Phonetic, Transliteration, & International)
# Format: (Correct version, [Common ASR/Wrong versions])
# Refined to include ONLY variants that are phonetically near-identical or pure orthographic variants.
NAME_VARIATIONS = [
    # Western/Anglo names
    ("Michael", ["Micheal", "Michaell", "Micahel"]),
    ("Catherine", ["Katherine", "Cathryn", "Catharine"]),
    ("Elizabeth", ["Elisabeth"]),
    ("Sarah", ["Sara"]),
    ("Steven", ["Stephen"]),
    ("Mark", ["Marc"]),
    ("Geoffrey", ["Jeffrey"]),
    ("Brian", ["Bryan"]),
    ("Sean", ["Shawn", "Shaun"]),
    ("Jon", ["John"]),
    ("Philip", ["Phillip"]),
    ("Allan", ["Alan", "Allen"]),
    ("Justin", ["Justyn"]),
    ("Matthew", ["Mathew", "Mattew"]),
    ("Nicholas", ["Nicolas", "Nikolas", "Nickolas"]),
    ("Gregory", ["Gregg"]),
    ("Anthony", ["Antony"]),
    ("Paul", ["Paull"]),
    ("Stephen", ["Steven"]),
    ("Jennifer", ["Jenifer", "Jeniffer", "Jenniffer"]),
    ("Jessica", ["Jesica", "Jessika"]),
    ("Emily", ["Emilie", "Emilly"]),
    ("Ashley", ["Ashleigh", "Ashlee", "Ashlie", "Ashli"]),
    ("Megan", ["Meghan", "Meagan"]),
    ("Amanda", ["Amandah", "Amandha"]),
    ("Kimberly", ["Kimberley"]),
    ("Lauren", ["Lauryn"]),
    ("Danielle", ["Daniell"]),
    ("Rachel", ["Rachael"]),
    ("Rebecca", ["Rebekah"]),
    ("Michelle", ["Michele"]),
    ("Melissa", ["Mellisa", "Melisa"]),
    ("Samantha", ["Samanta"]),
    ("Stephanie", ["Stefanie", "Stefani"]),
    ("Crystal", ["Krystal", "Cristal"]),
    ("Erin", ["Eryn", "Erinn"]),
    ("Shannon", ["Shanon"]),
    ("Lindsey", ["Lindsay", "Lynsey", "Lindsy"]),
    ("Courtney", ["Kourtney", "Courteney", "Courtnee"]),
    ("Kelsey", ["Kelsie", "Kelsy", "Kelsi"]),
    ("Brittany", ["Britney", "Brittney", "Britany", "Brittani", "Brittny"]),
    ("Brianna", ["Briana", "Bryanna"]),
    ("Morgan", ["Morgann", "Morghan"]),
    ("Sierra", ["Cierra"]),
    ("Chelsea", ["Chelsey", "Chelsee", "Chelsie"]),
    ("Alyssa", ["Alissa", "Alisa"]),
    ("Hailey", ["Haley", "Hayley", "Haily", "Hailee"]),
    ("Alexis", ["Alexas", "Alexes"]),
    ("Kaitlyn", ["Katelyn", "Kaitlin", "Caitlyn", "Kaitlynn", "Katelynn", "Caitlin", "Kaitlan", "Katelin"]),
    ("Erica", ["Erika"]),
    ("Kristen", ["Kristin", "Cristen", "Cristin"]),
    ("Tiffany", ["Tiffani", "Tiffanie"]),
    ("Leslie", ["Lesley"]),
    ("Monica", ["Monika"]),
    ("Natalie", ["Natalee", "Natali"]),
    ("Michaela", ["Michaella"]),
    ("Kristina", ["Christina", "Cristina"]),
    ("Lillian", ["Lilian"]),
    ("Madeline", ["Madelyn", "Madeleine"]),
    ("Gabrielle", ["Gabriela", "Gabriella"]),
    ("Isabel", ["Isabelle", "Isabell"]),
    ("Violet", ["Violette"]),
    ("Lila", ["Lilah"]),
    ("Aidan", ["Aiden", "Aadan"]),
    ("Connor", ["Conor", "Konnor"]),
    ("Brendan", ["Brendin", "Brendyn", "Brandan"]),
    ("Zachary", ["Zachery", "Zackary"]),
    ("Cameron", ["Camron", "Kameron"]),
    ("Jackson", ["Jaxon", "Jaxson", "Jakson"]),
    ("Christopher", ["Kristoffer", "Cristopher"]),
    ("Russell", ["Russel"]),
    ("Trevor", ["Trever"]),
    ("Garrett", ["Garett", "Garret"]),
    ("Blake", ["Blaike"]),
    ("Tanner", ["Taner"]),
    ("Caleb", ["Kaleb"]),
    ("Colin", ["Collin"]),
    ("Derek", ["Derrick", "Derrek", "Derik", "Derick"]),
    ("Mitchell", ["Mitchel"]),
    ("Shane", ["Shayne"]),
    ("Gabriel", ["Gabriele"]),
    ("Christian", ["Cristian", "Kristian"]),
    ("Lucas", ["Lukas"]),
    ("Isaac", ["Issac"]),
    ("Eric", ["Erik"]),
    ("Julian", ["Julien"]),
    ("Noah", ["Noa"]),
    ("Thomas", ["Tomas"]),
    ("Simon", ["Symon"]),
    ("Louis", ["Lewis", "Luis"]),
    ("Samuel", ["Samual"]),
    ("Andrew", ["Andru"]),
    ("Martin", ["Martyn"]),
    ("Frederick", ["Fredrick", "Fredrik"]),
    ("Alexander", ["Aleksander", "Aleksandr", "Alexandre"]),
    ("Robert", ["Robbert"]),
    ("Angela", ["Angella"]),
    ("Valerie", ["Valarie"]),
    ("Caroline", ["Karoline"]),
    ("Sophie", ["Sophy"]),
    ("Eleanor", ["Elinor", "Elanor", "Elenor"]),

    # East Asian Names (focusing on near-homophonous Romanization)
    ("Xiao", ["Hsiao"]),
    ("Wei", ["Way"]),
    ("Mei", ["May", "Mae"]),
    ("Jian", ["Jyan"]),
    ("Ming", ["Meeng"]),
    ("Qing", ["Ching"]),
    ("Wen", ["Wun"]),
    ("Yu", ["You", "Yoo"]),
    ("Li", ["Lee"]),
    ("Lin", ["Lynn", "Linn"]),
    ("Tian", ["Tyen", "Tien"]),
    ("Bo", ["Boh"]),
    ("Jun", ["June", "Joon"]),
    ("Kai", ["Kye"]),
    ("Jia", ["Jiya"]),
    ("Hua", ["Wah"]),
    ("Quan", ["Quon"]),
    ("Shan", ["Shaan"]),
    ("Cheng", ["Ching"]),
    ("Lu", ["Loo"]),
    ("Long", ["Lung"]),
    ("Guo", ["Kuo"]),
    ("Zhou", ["Chou"]),
    ("Cai", ["Tsai"]),
    ("Qian", ["Chien"]),

    # Japanese
    ("Yuki", ["Yuuki"]),
    ("Hiroshi", ["Hiroushi"]),
    ("Kenji", ["Kenjy"]),
    ("Satoshi", ["Satoushi"]),
    ("Takeshi", ["Takeshy"]),
    ("Kaito", ["Kaitoh"]),
    ("Sho", ["Shou", "Shouh"]),
    ("Kazu", ["Kazoo"]),
    ("Shin", ["Sheen"]),
    ("Riku", ["Ricku", "Rikku"]),
    ("Mai", ["My"]),

    # Korean
    ("Jihoon", ["Ji-hoon", "Jihun", "Jeehoon", "Ji Hun", "Ji Hun", "Jihuyn"]),
    ("Minji", ["Min-ji", "Minjee", "Min Ji", "Minjie", "Minje"]),
    ("Soojin", ["Su-jin", "Sujin", "Soojeen", "Soo Jin", "Soo-jin", "Soojinne"]),
    ("Hyun", ["Hyeon", "Hyoun", "Heon", "Hyunn"]),
    ("Joon", ["Jun", "June", "Joone", "Joonh"]),
    ("Sangwoo", ["Sang-woo", "Sang Woo", "Sangwu", "Sangwou"]),
    ("Yeji", ["Ye Ji", "Yejy", "Yejee", "Yehji"]),
    ("Seung", ["Sung", "Seong", "Seungh"]),
    ("Jisoo", ["Ji-soo", "Ji Soo", "Jisu", "Jeesoo", "Jisou"]),
    ("Hana", ["Hanna", "Ha-na", "Hannae", "Hanah"]),
    ("Taeyoung", ["Tae-young", "Tae Young", "Taeyong", "Teayoung"]),
    ("Kyung", ["Gyung", "Kyong", "Ky-eung", "Kyungg"]),
    ("Donghyun", ["Dong-hyun", "Dong Hyun", "Donghyeon", "Dongyun"]),
    ("Eunji", ["Eun-ji", "Unji", "Eun Ji", "Eunjy"]),
    ("Yuna", ["Yoona", "Yunna", "Yu-na", "Yunha"]),
    ("Haesoo", ["Hae-soo", "Hae Soo", "Haesu", "Haesu"]),
    ("Jimin", ["Ji-min", "Ji Min", "Jimeen", "Jimean"]),
    ("Seojin", ["Seo-jin", "Seo Jin", "Sujin", "Seojine"]),

    # Indian/South Asian
    ("Priya", ["Preeya", "Preea", "Priyaa"]),
    ("Sanjay", ["Sanjai"]),
    ("Amit", ["Ameet"]),
    ("Rohan", ["Rohaan"]),
    ("Anjali", ["Anjalee"]),
    ("Krishna", ["Krishnaa"]),
    ("Vikram", ["Vicram"]),
    ("Nikhil", ["Nikil", "Nikhill", "Nikheel"]),
    ("Arjun", ["Arjoon", "Arjunn"]),
    ("Ishaan", ["Ishan"]),
    ("Srini", ["Sreeni"]),
    ("Bharath", ["Bharat"]),
    ("Abhishek", ["Abishek", "Abhishekh"]),
    ("Aarav", ["Arav"]),
    ("Ananya", ["Anannya"]),
    ("Lakshmi", ["Laxmi", "Laksmi", "Laxhmi", "Lakshmy"]),
    ("Rahul", ["Rahool"]),
    ("Suman", ["Sooman"]),
    ("Sunil", ["Soonil"]),
    ("Deepak", ["Dipak"]),
    ("Ajay", ["Ajai"]),
    ("Preeti", ["Preety", "Priti"]),

    # Russian/Eastern European
    ("Alexei", ["Alexey", "Aleksei", "Aleksey"]),
    ("Elena", ["Yelena"]),
    ("Olga", ["Olha"]),
    ("Ekaterina", ["Yekaterina"]),
    ("Natalia", ["Nataliya", "Natalya"]),
    ("Dmitry", ["Dmitri", "Dimitri"]),
    ("Sergey", ["Sergei"]),
    ("Tatiana", ["Tatyana", "Tatiyana", "Tetyana"]),
    ("Valeria", ["Valeriya", "Valerya"]),
    ("Boris", ["Borys", "Borris"]),
    ("Kirill", ["Kiryl", "Kyrylo"]),
    ("Mikhail", ["Mikhael"]),
    ("Vladimir", ["Wladimir", "Vladymyr"]),
    ("Evgeny", ["Yevgeniy", "Yevgeny"]),
    ("Andrey", ["Andrei"]),
    ("Yulia", ["Yuliya", "Yulya"]),
    ("Oksana", ["Oxana", "Aksana"]),
    ("Pavel", ["Pavlo"]),
    ("Svetlana", ["Svitlana", "Swetlana"]),
    ("Maxim", ["Maksim", "Maxym"]),
    ("Yosef", ["Yoseph"]),
    ("Igor", ["Ihor"]),

    # Arabic/Middle Eastern
    ("Amina", ["Ameena", "Amena", "Aaminah"]),
    ("Fatima", ["Fateema", "Fatimah", "Fathima"]),
    ("Layla", ["Leila", "Lailah", "Leyla", "Laila"]),
    ("Omar", ["Omer", "Omaar"]),
    ("Yusuf", ["Yousuf", "Youssouf", "Yousef", "Yusef"]),
    ("Sami", ["Samy", "Samee"]),
    ("Samir", ["Sameer", "Samyr"]),
    ("Jamal", ["Jamaal"]),
    ("Ahmed", ["Ahmad", "Ahamd"]),
    ("Hassan", ["Hasan", "Hassaan", "Hassen"]),
    ("Rania", ["Ranya", "Raniya"]),
    ("Nadia", ["Nadya", "Nadiya"]),
    ("Karim", ["Kareem", "Carim"]),
    ("Zainab", ["Zaynab", "Zeynep"]),
    ("Qasim", ["Kasim", "Qassem", "Kasem"]),
    ("Ali", ["Aly", "Alee", "Aali"]),
    ("Rabia", ["Rabiya", "Rabya", "Rabiah"]),
    ("Farida", ["Fareeda", "Fareedah"]),

    # African
    ("Chiwetel", ["Chewetel"]),
    ("Ngozi", ["Ngozy"]),
    ("Kwame", ["Kwami", "Quame"]),
    ("Ayo", ["Ayoh"]),
    ("Olu", ["Olou"]),
    ("Thandiwe", ["Tandiwe", "Thandiewe"]),
    ("Abebe", ["Abebey"]),
    ("Kofi", ["Kofe"]),
    ("Sibongile", ["Sibongille"]),

    # Irish/Celtic/Scottish/Welsh
    ("Caitlin", ["Kaitlin", "Caitlyn", "Katelyn", "Caitlín"]),
    ("Niamh", ["Neve", "Nieve", "Neev", "Niav"]),
    ("Siobhan", ["Shevonne", "Shivon", "Shavonne", "Shivonne"]),
    ("Aoife", ["Eefa"]),
    ("Saoirse", ["Sersha", "Seersha", "Saoirsa"]),
    ("Padraig", ["Padraic", "Padric"]),
    ("Cian", ["Kian"]),
    ("Fionn", ["Finn"]),
    ("Deirdre", ["Deirdra"]),
    ("Roisin", ["Rosheen"]),

    # French
    ("Beatrice", ["Béatrice"]),
    ("Laurent", ["Laurens"]),
    ("Gabrielle", ["Gabriele"]),
    ("Celine", ["Selene", "Céline"]),
    ("Isabelle", ["Isabell"]),
    ("Pierre", ["Piere", "Pier"]),
    ("René", ["Rene"]),
    ("Jacques", ["Jaque"]),
    ("Thierry", ["Therry"]),

    # Germanic/Nordic
    ("Andreas", ["Andres"]),
    ("Johann", ["Johan"]),
    ("Matthias", ["Mathias", "Matias"]),
    ("Emil", ["Emile"]),
    ("Kristoffer", ["Kristof"]),

    # Italian/Spanish/Portuguese
    ("Giuseppe", ["Guiseppe"]),
    ("Rafael", ["Rafaël", "Raphael"]),
    ("Jose", ["Josep"]),
    ("Luis", ["Luiz", "Luís"]),
    ("Pedro", ["Petro"]),
    ("Xavier", ["Zavier", "Javier"]),

    # Miscellaneous
    ("Kaelyn", ["Kaylin", "Cailyn", "Kaelin", "Kailyn", "Caelyn"]),
    ("Jayden", ["Jaden", "Jaiden", "Jaidan", "Jaeden", "Jaydon"]),
    ("Zoey", ["Zoe", "Zoë", "Zooey", "Zowie"]),
    ("Aaliyah", ["Aliyah", "Aaliya", "Aleah"]),
    ("Nevaeh", ["Neveah", "Nevayah"]),
    ("Mila", ["Milla", "Meela"]),
    ("Luca", ["Lucca", "Luka"]),
    ("Myles", ["Miles"]),
    ("Jace", ["Jayce", "Jase"]),
    ("Khloe", ["Chloe", "Kloey", "Khloé"]),
    ("Jaxon", ["Jackson", "Jaxson", "Jakson"]),
    ("Adeline", ["Adaline", "Adalyn", "Adalynn"]),
    ("Peyton", ["Payton", "Paiton"]),
    ("Scarlett", ["Scarlet", "Scarlette"]),

    # Stage/celebrity spelling variants
    ("The Weeknd", ["The Weekend"]),
    ("Beyoncé", ["Beyonce"]),
    ("Rihanna", ["Rhianna"]),
    ("Snoop Dogg", ["Snooop Dog", "Snoop Dog"]),
    ("Zendaya", ["Zendya"]),
    ("Macklemore", ["Mackelmore"]),

    # Fantasy & Sci-Fi
    ("Daenerys", ["Denarys"]),
    ("Tyrion", ["Tyrian"]),
    ("Arya", ["Aria", "Aarya"]),
    ("Brienne", ["Briene"]),
    ("Rhaenyra", ["Raniera", "Rhaenira"]),
    ("Galadriel", ["Galadrial"]),
    ("Thanos", ["Tanos", "Thannos"]),
    ("Loki", ["Loakie"]),

    # Diacritics/International
    ("Renée", ["Renee", "Reneé", "Renèe"]),
    ("José", ["Jose", "Josè"]),
    ("Björk", ["Byork"]),
    ("Zoë", ["Zoe", "Zoey"]),
    ("Kylian", ["Killian", "Kilian"]),
    ("Mbappé", ["Mbappe"]),

    # Diverse dialect/phonetic confusion
    ("Elijah", ["Elyjah", "Elijha", "Alijah"]),
    ("Isaiah", ["Izaiah", "Isiah"]),
    ("Aaliyah", ["Aliyah", "Aleah", "Alia"]),
    ("Giovanni", ["Geovany", "Jovani", "Jovanni"]),
    ("Enrique", ["Enriqué", "Enrick"]),
    ("Andrés", ["Andres", "Andress", "Andrès"]),
    ("Camila", ["Kamila", "Camyla", "Cammila"]),
    ("León", ["Leon", "Leonn"]),
    ("Santiago", ["Santiagoo"]),
    ("María", ["Maria", "Mária"]),

    # Disambiguate names with one-letter missings
    ("Eli", ["Elli", "Ely"]),
    ("Max", ["Maks", "Macs", "Macks"]),
    ("Tom", ["Tomm"]),
    ("Anna", ["Ana", "Anah"]),
]

LAST_NAMES = [
    "Smith", "Johnson", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez", "Brown", 
    "Williams", "Jones", "Taylor", "Anderson", "Thomas", "Moore", "Jackson", "White", 
    "Harris", "Martin", "Thompson", "Young", "King", "Scott", "Green", "Adams", "Baker", 
    "Nelson", "Hill", "Ramirez", "Campbell", "Mitchell", "Roberts", "Carter", "Phillips", 
    "Evans", "Turner", "Torres", "Parker", "Collins", "Edwards", "Stewart", "Morris", 
    "Morales", "Murphy", "Cook", "Rogers", "Morgan", "Peterson", "Cooper", "Reed", "Bailey",
    "Patel", "Nguyen", "Kim", "Lee", "Khan", "Singh", "Tan", "Ivanov", "Schmidt", "Müller",
    "Rossi", "Lefebvre", "Dubois", "Silva", "Santos"
] + [
    # Global common surnames, including Western, East Asian, South Asian, and some rare
    "Kumar", "Gupta", "Sharma", "Singh", "Patil", "Reddy", "Ahmed", "Ali", "Chowdhury", "Rahman", "Zhang", "Wang",
    "Chen", "Liu", "Yang", "Zhao", "Huang", "Tan", "Lim", "Ong", "Chua", "Ng", "Goh", "Khoo", "Teo",
    "Koh", "Hong", "Lin", "Wu", "Sun", "Fang", "Xu", "He", "Ma", "Gao", "Lu", "Peng", "Wei",
    "Liang", "Zhu", "Zhou", "Deng", "Jiang", "Cai", "Qian", "Yu", "Lu", "Gao", "Pan", "Xie", "Han",
    "Kim", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Im", "Lee", "Jeong", "Lim", "Shin", "Jang",
    "Oh", "Seo", "Ahn", "Yu", "Moon", "Son", "Hwang", "Song", "Hong", "Yang", "Go", "Bae", "Baek", "Kwon",
    "Jin", "Nam", "Han", "Jo", "Sim", "Min", "No", "Ha", "Joo", "Jin", "Ma", "Seok", "Soo", "Dong",
    # European surnames
    "Smith", "Jones", "Taylor", "Brown", "Williams", "Wilson", "Johnson", "Evans", "Thomas", "Roberts", "Walker",
    "Wright", "Thompson", "Robinson", "White", "Edwards", "Hughes", "Green", "Hall", "Lewis", "Harris", "Clarke",
    "Allen", "Young", "King", "Scott", "Turner", "Carter", "Phillips", "Mitchell", "Campbell", "Parker", "James",
    "Bennett", "Morgan", "Gray", "Murphy", "Kelly", "Stewart", "Bell", "Cooper", "Richardson", "Bailey", "Cook",
    "Morris", "Ward", "Watson", "Brooks", "Wood", "Reed", "Holmes", "Graham", "Butler", "Davies", "Harrison",
    "Jackson", "Foster", "Chapman", "Murray", "Knight", "Barnes", "Wallace", "Gibson", "Russell", "Marshall",
    "Rose", "Pearson", "Black", "Palmer", "Matthews", "Grant", "Freeman", "Lawrence", "Harvey", "Burton", "Spencer",
    # French & other European
    "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau", "Simon",
    "Laurent", "Lefebvre", "Michel", "Garcia", "David", "Bertrand", "Roux", "Vincent", "Fournier", "Morel",
    "Girard", "Andre", "Lefevre", "Mercier", "Dupont", "Lambert", "Bonnet", "Francois", "Martinez", "Legrand",
    "Gonzalez", "Perez", "Lopez", "Sanchez", "Ramirez", "Torres", "Castro", "Fernandez", "Vargas", "Morales",
    "Silva", "Santos", "Oliveira", "Pereira", "Costa", "Rodrigues", "Alves", "Marques", "Barros", "Ribeiro",
    # Italian
    "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco",
    "Bruno", "Gallo", "Conti", "De Luca", "Mancini", "Costa", "Giordano", "Rizzo", "Lombardi", "Moretti",
    "Barbieri", "Fontana", "Santoro", "Mariani", "Rinaldi", "Caruso", "Ferrara", "Galli", "Martini",
    "Leone", "Longo", "Gentile",
    # German
    "Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann",
    "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun",
    "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier", "Lehmann",
    # Russian/East European & others
    "Ivanov", "Petrov", "Sidorov", "Smirnov", "Kuznetsov", "Popov", "Vasilyev", "Novikov", "Fedorov", "Mikhailov",
    "Morozov", "Volkov", "Semenov", "Egorov", "Pavlov", "Stepanov", "Nikolaev", "Orlov", "Andreev", "Timofeev",
    "Filipov", "Vinogradov", "Romanov", "Konstantinov", "Markov", "Mironov", "Gusev", "Lvov", "Gerasimov", "Bondarenko",
    "Tkachenko", "Kravchenko", "Shevchenko", "Melnik", "Polanski", "Nowak", "Kowalski", "Wojcik", "Kaminski", "Lewandowski",
    "Duda", "Baran", "Zielinski", "Szymanski", "Mazur", "Krawczyk", "Grabowski",
    # Middle Eastern/North African
    "Hassan", "Muhammad", "Yousef", "Samir", "Fahmy", "Ismail", "Saeed", "Bakr", "Khalil", "Farouk", "Mostafa",
    "Soliman", "Ibrahim", "Tarek", "Nassar", "Amin", "Haddad", "Moussa", "Omar", "Abdel", "Mahmoud", "Ashraf",
    "Aziz", "Hussein", "Farid", "Salim", "Fadl", "Elbaz", "Elmasry", "Kassir", "Nasr", "Saleh", "Rahim",
    # African
    "Nkosi", "Sibanda", "Ndlovu", "Dlamini", "Moyo", "Chirwa", "Okafor", "Abiola", "Olawale", "Ngugi", "Obasi",
    "Adeyemi", "Kamara", "Mensah", "Boateng", "Amadou", "Fofana", "Touré", "Diallo", "Coulibaly", "Keita", 
    "Ndiaye", "Fall", "Ba", "Diop", "Cissé", "Gueye",
    # Hispanic/Latin American
    "Gomez", "Jimenez", "Ruiz", "Herrera", "Medina", "Ortiz", "Moreno", "Gutierrez", "Chavez", "Ramos",
    "Vega", "Soto", "Castillo", "Cruz", "Silva", "Mendoza", "Delgado", "Aguilar", "Pena", "Iglesias", "Navarro",
    # Jewish/Hebrew
    "Levi", "Cohen", "Mizrahi", "Avraham", "Shapiro", "Rosenberg", "Katz", "Goldstein", "Friedman", "Weiss",
    "Eisen", "Goren", "Aharoni", "Ben-David", "Peretz", "Mor", "Hadad", "Barak", "Yosef", "Yehuda",
    # Scandinavian
    "Andersen", "Johansen", "Olsen", "Larsen", "Nilsen", "Hansen", "Pedersen", "Kristiansen", "Jensen", "Karlsen",
    "Nilsson", "Eriksson", "Karlsson", "Olsson", "Persson", "Svensson", "Gustafsson", "Lindberg", "Berg", "Lund",
    # Greek
    "Papadopoulos", "Nikolaidis", "Georgiou", "Pappas", "Dimitriou", "Economou", "Vassilakis",
    # Turkish
    "Yilmaz", "Kaya", "Demir", "Celik", "Sahin", "Yildiz", "Korkmaz", "Arslan",
    # Misc
    "Henderson", "Holm", "Fox", "Lane", "Stone", "Payne", "Rice", "Gill", "Fleming", "Wells", "Kennedy",
    "Ford", "Moss", "Ray", "Long", "Todd", "Francis", "Barrett", "Mitchell", "Wilkinson", "Dean",
    "Webb", "Cameron", "Barker", "Bryant", "Holt", "Matthews", "Chapman", "Porter", "Shaw", "Hudson", "Waters",
    "Pearce", "Francis", "Harper", "Norman", "Lyons", "Munro", "Sanders", "Stokes", "Reeve", "Holland",
    # Add more unique spellings and diaspora names for even greater diversity
    "Saadat", "Aminu", "Dalal", "Rizvi", "Varma", "Yamauchi", "Abidi", "Mendoza", "Sousa", "Lopes", "Andrade",
    "De La Cruz", "De Santis", "Del Rio", "Dos Santos", "Monteiro", "Longoria", "McCarthy", "O'Connor", "Macdonald",
    "Fitzgerald", "Sweeney", "Pereyra", "Varela", "MacLeod", "Sinclair", "McKenzie", "Drake", "Ortega", "Espinoza",
    "Figueroa", "Carvalho", "Rossi", "Ferreira", "Smithson", "Falk", "Voigt", "Sokolov", "Ivanenko", "Blanchard",
    # Famous/Pop culture (English and international)
    "Potter", "Granger", "Weasley", "Skywalker", "Kenobi", "Solo", "Organa", "Stark", "Banner", "Parker",
    "Wayne", "Kent", "Luthor", "Rogers", "Romanoff", "Maximoff", "Wilson", "Strange", "Xavier", "Grey",
    "Summers", "Lehnsherr", "Owens", "Reed", "Storm", "Drake", "Blake", "Grant", "Forrester"
]

# 3. EXPANDED ACTION TEMPLATES (Professional & Office Contexts)
TEMPLATES = [
    "Can you ask {wrong_name} to join the Zoom?",
    "I think {wrong_name} is handling the project.",
    "Is {wrong_name} on the call?",
    "{wrong_name}'s PR is ready for review.",
    "Did {wrong_name} send the report yet?",
    "I'll sync with {wrong_name} later today.",
    "Please send the invite to {wrong_name}.",
    "{wrong_name} mentioned the deadline was moved.",
    "Wait for {wrong_name} before starting the meeting.",
    "Check with {wrong_name} about the API credentials.",
    "Could you take a look at the PR from {wrong_name}?",
    "I'm waiting on {wrong_name} to approve the changes.",
    "{wrong_name} is first on the standup list.",
    "Has {wrong_name} updated their ticket?",
    "Let's find a time that works for {wrong_name}.",
    "I'll coordinate the meeting with {wrong_name}.",
    "{wrong_name} suggested we use a different database.",
    "Is {wrong_name} familiar with this part of the codebase?",
    "I'll follow up with {wrong_name} after the meeting.",
    "{wrong_name} is the point of contact for this.",
    "Please add {wrong_name} to the email thread.",
    "Did {wrong_name} finish the documentation for the new API?",
    "I need to discuss the roadmap with {wrong_name}.",
    "{wrong_name} found a bug in the production environment.",
    "Can {wrong_name} join the sync tomorrow morning?",
    "Ask {wrong_name} if they have the login for the staging server.",
    "I saw a comment from {wrong_name} on the design doc.",
    "{wrong_name} is leading the research on machine learning.",
    "We should get some feedback from {wrong_name} on this.",
    "I'm going to grab a coffee with {wrong_name} later.",
    "Did {wrong_name} mention anything about the budget?",
    "{wrong_name} is currently out of office until Monday.",
    "Please make sure {wrong_name} has access to the repository.",
    "I'll double check the numbers with {wrong_name}.",
    "{wrong_name} is the one who originally wrote this script.",
    "Can you pass the message to {wrong_name} for me?",
    "I'll be working closely with {wrong_name} on this feature.",
    "{wrong_name} has a lot of experience with React.",
    "Is {wrong_name} joining the happy hour tonight?",
    "I sent the draft to {wrong_name} for some initial thoughts.",
    "Please CC {wrong_name} on all future updates.",
    "{wrong_name} is presenting their findings at the all-hands.",
    "I'll ask {wrong_name} to walk us through the deployment process.",
    "Did {wrong_name} catch that error in the logs?",
    "{wrong_name} is the best person to talk to about this.",
    "I'll check the calendar to see when {wrong_name} is free.",
    "{wrong_name} suggested a few improvements to the UI.",
    "Has {wrong_name} reviewed the security policy yet?",
    "I'll sync up with {wrong_name} to make sure we're on the same page.",
    "{wrong_name} is taking the lead on the frontend refactor.",
    "Did {wrong_name} mention which branch to use?",
    "I'll need to get approval from {wrong_name} first.",
    "Can you tag {wrong_name} in the Jira ticket?",
    "I saw {wrong_name} in the kitchen earlier.",
    "Is {wrong_name} available for a huddle?",
    "I think {wrong_name} has the latest version of the deck.",
    "We should invite {wrong_name} to the session.",
    "Did {wrong_name} get the feedback from the client?",
    "{wrong_name} is working on the Q3 projections.",
    "I'll send the recording to {wrong_name} afterwards.",
    "Could {wrong_name} help us debug this issue?",
    "I'm waiting for a response from {wrong_name}.",
    "Did {wrong_name} say when the feature would be ready?",
    "{wrong_name} is going to be our new Scrum Master.",
    "I'll make sure to update {wrong_name} on our progress.",
    "Has {wrong_name} seen the new design system yet?",
    "I'll grab {wrong_name} if I have any more questions.",
    "Can {wrong_name} provide a summary of the meeting?",
    "I'll check with {wrong_name} before I merge the code.",
    "{wrong_name} is presenting at the conference next week.",
    "Did {wrong_name} find the root cause of the outage?",
    "I'll put {wrong_name} in touch with the sales team.",
    "Is {wrong_name} still on for our 1-on-1?",
    "I'll add {wrong_name}'s comments to the final report.",
    "{wrong_name} is the expert on our cloud infrastructure.",
    "Did {wrong_name} approve the holiday request?",
    "I'll send the meeting minutes to {wrong_name}.",
    "Can {wrong_name} help me with the SQL query?",
    "I'll be shadowing {wrong_name} for the rest of the week.",
    "{wrong_name} has some great ideas for the rebranding.",
    "Did {wrong_name} mention anything about the new policy?",
    "I'll make sure {wrong_name} is included in the email.",
    "Is {wrong_name} leading the next sprint planning?",
    "I'll check if {wrong_name} has any capacity for this.",
    "{wrong_name} is the primary reviewer for this document.",
    "Did {wrong_name} get the latest update from legal?",
    "I'll follow {wrong_name}'s lead on this one.",
    "Can {wrong_name} walk me through the architecture?",
    "I'll sync with {wrong_name} on the marketing strategy.",
    "{wrong_name} is our go-to for any Python questions.",
    "Did {wrong_name} sign off on the technical spec?",
    "I'll double check with {wrong_name} about the time.",
    "Is {wrong_name} taking notes during the session?",
    "I'll make sure {wrong_name} has the right permissions.",
    "{wrong_name} is coordinating the team building event.",
    "Did {wrong_name} share the results of the A/B test?",
    "I'll talk to {wrong_name} about the resource allocation.",
    "Can {wrong_name} give us a demo of the new tool?",
    "I'll be reporting to {wrong_name} for this project.",
    "{wrong_name} is finishing up the user research.",
    "Did {wrong_name} mention the budget constraints?",
    "I'll send the calendar invite to {wrong_name} now.",
    "Is {wrong_name} okay with the proposed timeline?",
    "I'll check {wrong_name}'s availability for the interview.",
    "{wrong_name} is updating the employee handbook.",
    "Did {wrong_name} receive the signed contract?",
    "I'll ask {wrong_name} to provide some context on this.",
    "Can {wrong_name} help with the data migration?",
    "I'll loop in {wrong_name} if we need more expertise.",
    "{wrong_name} is managing the relationship with the vendor.",
    "Did {wrong_name} catch the typo in the presentation?",
    "I'll make sure {wrong_name} is aware of the change.",
    "Is {wrong_name} planning the product launch?",
    "I'll check the dashboard with {wrong_name}.",
    "{wrong_name} is analyzing the latest churn rates.",
    "Did {wrong_name} mention the feedback from the board?",
    "I'll get a second opinion from {wrong_name}.",
    "Can {wrong_name} help me format the spreadsheet?",
    "I'll be working out of the same office as {wrong_name}.",
    "{wrong_name} is setting up the automated tests.",
    "Did {wrong_name} find a solution for the memory leak?",
    "I'll send the draft to {wrong_name} for review.",
    "Is {wrong_name} attending the workshop tomorrow?",
    "I'll make sure {wrong_name} has the login details.",
    "{wrong_name} is writing the post-mortem for the incident.",
    "Did {wrong_name} approve the reimbursement?",
    "I'll sync with {wrong_name} on the hiring plan.",
    "Can {wrong_name} explain the logic behind this?",
    "I'll be attending {wrong_name}'s talk at the meetup.",
    "{wrong_name} is organizing the code review schedule.",
    "Did {wrong_name} see the notification in Slack?",
    "I'll check with {wrong_name} about the hardware requirements.",
    "Is {wrong_name} still working on the documentation?",
    "I'll make sure {wrong_name} is invited to the lunch.",
    "{wrong_name} is our lead security engineer.",
    "Did {wrong_name} mention the new customer feedback?",
    "I'll get {wrong_name}'s thoughts on the proposal.",
    "Can {wrong_name} help me with the onboarding?",
    "I'll be collaborating with {wrong_name} on the research.",
    "{wrong_name} is preparing the slides for the demo.",
    "Did {wrong_name} find the missing file?",
    "I'll check {wrong_name}'s schedule for a meeting.",
    "Is {wrong_name} happy with the current progress?",
    "I'll make sure {wrong_name} has the latest API docs.",
    "{wrong_name} is the main architect for the system.",
    "Did {wrong_name} approve the change request?",
    "I'll talk to {wrong_name} about the project scope.",
    "Can {wrong_name} provide some feedback on the PR?",
    "I'll be sitting next to {wrong_name} today.",
    "{wrong_name} is looking into the performance issues.",
    "Did {wrong_name} mention the new project deadline?",
    "I'll send the report to {wrong_name} by EOD.",
    "Is {wrong_name} available for a quick sync?",
    "I'll check the logs with {wrong_name} later.",
    "{wrong_name} is our resident expert on accessibility.",
    "Did {wrong_name} get the invitation to the offsite?",
    "I'll make sure {wrong_name} is on the distribution list.",
    "Can {wrong_name} help me with the deployment?",
    "I'll be working with {wrong_name} on the refactor.",
    "{wrong_name} is presenting the roadmap today.",
    "Did {wrong_name} approve the budget increase?",
    "I'll talk to {wrong_name} about the team's capacity.",
    "Is {wrong_name} joining the call from home?",
    "I'll check {wrong_name}'s calendar for a free slot.",
    "{wrong_name} is finishing up the design specs.",
    "Did {wrong_name} see the latest sales figures?",
    "I'll make sure {wrong_name} has access to the tool.",
    "Can {wrong_name} walk us through the user journey?",
    "I'll be syncing with {wrong_name} every morning.",
    "{wrong_name} is our point of contact for HR.",
    "Did {wrong_name} catch the bug in the staging area?",
    "I'll get {wrong_name}'s signature on the document.",
    "Is {wrong_name} leading the discussion on strategy?",
    "I'll check with {wrong_name} about the lunch order.",
    "{wrong_name} is our most senior developer.",
    "Did {wrong_name} mention the new client requirement?",
    "I'll talk to {wrong_name} about the office layout.",
    "Can {wrong_name} help me troubleshoot the connection?",
    "I'll be presenting alongside {wrong_name}.",
    "{wrong_name} is writing the script for the tutorial.",
    "Did {wrong_name} approve the travel request?",
    "I'll sync with {wrong_name} on the product vision.",
    "Is {wrong_name} available to review my code?",
    "I'll check with {wrong_name} about the dress code.",
    "{wrong_name} is our lead data scientist.",
    "Did {wrong_name} mention the upcoming team meeting?",
    "I'll talk to {wrong_name} about the mentorship program.",
    "Can {wrong_name} help me set up the development environment?",
    "I'll be working with {wrong_name} on the backend.",
    "{wrong_name} is coordinating the office relocation.",
    "Did {wrong_name} approve the software license?",
    "I'll talk to {wrong_name} about the career development plan.",
    "Is {wrong_name} joining the team for dinner?",
    "I'll check {wrong_name}'s availability for the demo.",
    "{wrong_name} is drafting the mission statement.",
    "Did {wrong_name} see the new brand guidelines?",
    "I'll talk to {wrong_name} about the diversity initiative.",
    "Can {wrong_name} help me with the expense report?",
    "I'll be collaborating with {wrong_name} on the API.",
    "{wrong_name} is leading the efforts on documentation.",
    "Did {wrong_name} catch the error in the spreadsheet?",
    "I'll check with {wrong_name} about the holiday schedule.",
    "Is {wrong_name} attending the training session?",
    "I'll make sure {wrong_name} has the meeting link.",
    "{wrong_name} is our project manager for this sprint.",
    "I'll sync with {wrong_name} later. We also need to loop in {other_name} for the design review. Let me know if you can join.",
    "Please send the invite to {wrong_name}. They'll be joining {other_name} and {another_name} for the project sync tomorrow morning.",
    "{wrong_name} mentioned the deadline was moved. Did {other_name} confirm that with you? We need to update the Jira ticket ASAP.",
    "Check with {wrong_name} about the API credentials. {other_name} said they might be expired or restricted for the staging environment.",
    "I'm waiting on {wrong_name} to approve the changes. Once that's done, {other_name} can merge the PR and notify the team.",
    "{wrong_name} is first on the standup list. Then it'll be {other_name} and finally {another_name}. Please keep your updates brief today.",
    "Let's find a time that works for {wrong_name}. I'll check with {other_name} to see if they're free for a quick huddle at 3 PM.",
    "I saw {wrong_name} in the kitchen earlier. They were talking to {other_name} about the upcoming team offsite in Tahoe.",
    "{wrong_name} is leading the research on machine learning. {other_name} is assisting with the data collection and cleaning process.",
    "Hey {other_name}, can you check with {wrong_name} if the build is green? I'm seeing some strange failures in the CI pipeline.",
    "We have a meeting with {wrong_name}, {other_name}, and {another_name} at 2 PM. Please bring the latest version of the analytics report.",
    "{wrong_name} is going to be our new Scrum Master. {other_name} will be taking over as the main Product Owner for this squad.",
    "Can {wrong_name} provide a summary of the meeting? {other_name} couldn't make it today because of a conflicting client call.",
    "{wrong_name} is the expert on our cloud infrastructure. {other_name} usually handles the local setup and Docker configurations.",
    "I'll be shadowing {wrong_name} for the rest of the week. {other_name} will be my main point of contact for any HR related questions.",
    "Did {wrong_name} sign off on the technical spec? {other_name} needs it for the backend implementation phase starting on Monday.",
    "Can {wrong_name} give us a demo of the new tool? {other_name} and {another_name} are keen to see how it integrates with Slack.",
    "I'll check {wrong_name}'s availability for the interview. {other_name} will also be on the panel to evaluate the candidate's technical skills.",
    "Did {wrong_name} receive the signed contract? {other_name} sent it over yesterday via Docusign for final signature.",
    "I'll loop in {wrong_name} if we need more expertise. {other_name} suggested they might have some context on the legacy codebase.",
    "Is {wrong_name} planning the product launch? {other_name} is coordinating with the PR agency to finalize the press release schedule.",
    "{wrong_name} is writing the post-mortem for the incident. {other_name} is collecting the logs and system metrics from Grafana for the report.",
    "I'll sync with {wrong_name} on the hiring plan. {other_name} has some great candidates in mind for the open frontend developer role.",
    "{wrong_name} is our lead security engineer. {other_name} handles the network security and firewall rules for the production VPC.",
    "I'll be collaborating with {wrong_name} on the user research. {other_name} will provide the data sets and historical context for the project.",
    "{wrong_name} is the main architect for the system. {other_name} is the database lead and handles all major schema migrations.",
    "Is {wrong_name} leading the discussion on strategy? {other_name} and {another_name} will be participating as key stakeholders in the session.",
    "I'll talk to {wrong_name} about the career development plan. {other_name} has already had their mid-year review with the manager last week.",
    "Can {wrong_name} help me troubleshoot the connection? {other_name} said it might be a DNS issue or a routing misconfiguration.",
    "I'll check with {wrong_name} about the holiday schedule. {other_name} thought the office was closed on Friday for the long weekend.",
    "I'll grab {wrong_name} for the meeting. {other_name} is already waiting in the conference room. We should start in five minutes.",
    "Did {wrong_name} mention the feedback from {other_name}? They were both in the client meeting this morning discussing the roadmap.",
    "I need {wrong_name} to review this document. {other_name} has already looked at it, but we need a second pair of eyes.",
    "Has {wrong_name} updated their ticket? {other_name} needs the status for the weekly report. Can you follow up with them?",
    "I'll coordinate the sync with {wrong_name}. {other_name} mentioned that 4 PM might be a good time for everyone to meet.",
    "{wrong_name} suggested we use a different database. {other_name} has some concerns about the migration cost. What do you think?",
    "Is {wrong_name} familiar with this part of the code? {other_name} said they might have written the original implementation last year.",
    "I'll follow up with {wrong_name} after the call. {other_name} wants to make sure we're on track for the release.",
    "{wrong_name} is the point of contact for this project. Reach out to them or {other_name} if you have any questions.",
    "Please add {wrong_name} to the thread. {other_name} and {another_name} are already participating in the discussion.",
    "Did {wrong_name} finish the documentation? {other_name} is waiting to start the integration and needs the API endpoints.",
    "I need to discuss the roadmap with {wrong_name}. {other_name} will be leading the effort next quarter for the mobile team.",
    "{wrong_name} found a bug in production. They're working with {other_name} on a fix. We hope to deploy by EOD.",
    "Can {wrong_name} join the huddle tomorrow? {other_name} has some updates on the frontend refactor that everyone should hear.",
    "Ask {wrong_name} if they have the credentials. {other_name} lost their access yesterday and can't log in to the server.",
    "I saw a comment from {wrong_name} on the PR. {other_name} already replied to it, but there are still some open questions.",
    "We should get some feedback from {wrong_name}. {other_name} and {another_name} have already weighed in on the new design.",
    "I'm going to grab lunch with {wrong_name}. Do you want to join us, {other_name}? We're heading out in ten minutes.",
    "Did {wrong_name} mention the budget? {other_name} is getting nervous about the projections for the next fiscal year.",
    "{wrong_name} is OOO until Monday. Please talk to {other_name} if you need immediate assistance with the deployment.",
    "Please make sure {wrong_name} has access to the repo. {other_name} is handling the permissions for the new hires.",
    "I'll double check the numbers with {wrong_name}. {other_name} thought they looked a bit off in the latest spreadsheet.",
    "{wrong_name} is the one who originally wrote this script. {other_name} has been maintaining it for the past few months.",
    "Can you pass the message to {wrong_name}? Tell them that {other_name} is looking for the report from last week.",
    "I'll be working closely with {wrong_name} on this. {other_name} will be our project manager for the duration of the pilot.",
    "{wrong_name} has a lot of experience with React. Maybe they can help {other_name} with the tricky UI bugs we found.",
    "Is {wrong_name} joining the happy hour? {other_name} and {another_name} are already there at the bar around the corner.",
    "I sent the draft to {wrong_name} for initial thoughts. {other_name} will provide the final sign-off before we publish.",
    "Please CC {wrong_name} on all updates. {other_name} is tracking the progress for the board meeting next Tuesday.",
    "{wrong_name} is presenting at the all-hands. {other_name} will be introducing them and facilitating the Q&A section.",
    "I'll ask {wrong_name} to walk us through the process. {other_name} needs to learn it too for the upcoming audit.",
    "Did {wrong_name} catch that error in the logs? {other_name} said it was related to the database connection pool.",
    "{wrong_name} is the best person to talk to about this. {other_name} recommended them highly for their domain expertise.",
    "I'll check the calendar to see when {wrong_name} is free. {other_name} is also very busy this week with the launch.",
    "{wrong_name} suggested a few UI improvements. {other_name} is already implementing them in the latest branch.",
    "Has {wrong_name} reviewed the security policy? {other_name} is waiting for the green light to start the scan.",
    "I'll sync up with {wrong_name} to make sure we're aligned. {other_name} will join us to provide the product context.",
    "{wrong_name} is taking the lead on the refactor. {other_name} is handling the state management and data fetching.",
    "I'll check the dashboard with {wrong_name}. {other_name} said the metrics were looking good after the latest patch.",
    "{wrong_name} is analyzing the latest churn rates. {other_name} is looking at user engagement metrics in parallel.",
    "Did {wrong_name} mention the board feedback? {other_name} was in the meeting too and took some detailed notes.",
    "I'll get a second opinion from {wrong_name}. {other_name} has a different perspective on the architectural trade-offs.",
    "Can {wrong_name} help me with the spreadsheet? {other_name} showed me a few tricks last week that were very helpful.",
    "I'll be working out of the SF office with {wrong_name}. {other_name} is based in New York and will join us remotely.",
    "{wrong_name} is setting up the automated tests. {other_name} is writing the unit tests for the core business logic.",
    "Did {wrong_name} find a solution for the leak? {other_name} is still investigating the heap dumps from production.",
    "I'll send the draft to {wrong_name} for review. {other_name} will be the second reviewer for the technical accuracy.",
    "Is {wrong_name} attending the workshop? {other_name} and {another_name} are already signed up for the morning session.",
    "I'll make sure {wrong_name} has the login details. {other_name} will provide the VPN access instructions separately.",
    "{wrong_name} is writing the post-mortem. {other_name} is collecting the timelines from the Slack incident channel.",
    "Did {wrong_name} approve the reimbursement? {other_name} is handling the finance approvals for the team this month.",
    "I'll sync with {wrong_name} on the hiring plan. {other_name} has some great candidates from their previous company.",
    "Can {wrong_name} explain the logic? {other_name} was having some trouble following the complex nested loops.",
    "I'll be attending {wrong_name}'s talk. {other_name} is also going to be there to support and take pictures.",
    "{wrong_name} is organizing the code review. {other_name} will manage the assignments to ensure even distribution.",
    "Did {wrong_name} see the Slack notification? {other_name} sent it about an hour ago regarding the server maintenance.",
    "I'll check with {wrong_name} about the hardware. {other_name} needs to order the new MacBook Pros for the interns.",
    "Is {wrong_name} still working on the docs? {other_name} said it was almost done and ready for a final proofread.",
    "I'll make sure {wrong_name} is invited. {other_name} is picking the restaurant for our celebratory team lunch.",
    "{wrong_name} is our lead security engineer. {other_name} handles the network infrastructure and firewall policies.",
    "Did {wrong_name} mention the customer feedback? {other_name} was very pleased with the positive reviews we received.",
    "I'll get {wrong_name}'s thoughts on the proposal. {other_name} has already shared their initial concerns with me.",
    "Can {wrong_name} help me with onboarding? {other_name} is my assigned mentor for the first three months.",
    "I'll be collaborating with {wrong_name}. {other_name} will provide the data sets and API documentation we need.",
    "{wrong_name} is preparing the slides. {other_name} is recording the video demo to include in the presentation.",
    "Did {wrong_name} find the missing file? {other_name} thought it was in the shared Google Drive folder.",
    "I'll check {wrong_name}'s schedule. {other_name} suggested a time on Thursday afternoon that works for everyone.",
    "Is {wrong_name} happy with the progress? {other_name} thinks we're actually ahead of schedule for once.",
    "I'll make sure {wrong_name} has the API docs. {other_name} updated them this morning with the new endpoints.",
    "{wrong_name} is the main system architect. {other_name} is the database lead and handles the SQL optimizations.",
    "Did {wrong_name} approve the change? {other_name} is waiting for the final sign-off before merging to master.",
    "I'll talk to {wrong_name} about the scope. {other_name} mentioned some potential risks with the current timeline.",
    "Can {wrong_name} provide feedback on the PR? {other_name} has already reviewed the architectural approach.",
    "I'll be sitting next to {wrong_name}. {other_name} is at the desk across from us if you need them too.",
    "{wrong_name} is looking into performance. {other_name} is profiling the slow database queries in the dev environment.",
    "Did {wrong_name} mention the deadline? {other_name} said it was non-negotiable because of the marketing campaign.",
    "I'll send the report to {wrong_name}. {other_name} needs it for the board meeting first thing tomorrow morning.",
    "Is {wrong_name} available for a sync? {other_name} has a question about the roadmap for the next sprint.",
    "I'll check the logs with {wrong_name}. {other_name} is currently busy with another urgent production incident.",
    "{wrong_name} is our accessibility expert. {other_name} is focusing on the internationalization of the web app.",
    "Did {wrong_name} get the offsite invite? {other_name} is still waiting for their confirmation from the organizer.",
    "I'll make sure {wrong_name} is on the list. {other_name} should also be included in the distribution group.",
    "Can {wrong_name} help with the deployment? {other_name} is OOO today and we need to push the hotfix.",
    "I'll be working with {wrong_name}. {other_name} will be overseeing the whole refactoring process as the lead.",
    "{wrong_name} is presenting the roadmap. {other_name} will be handling the Q&A session at the end.",
    "Did {wrong_name} approve the increase? {other_name} is very happy about the news for the team's budget.",
    "I'll talk to {wrong_name} about capacity. {other_name} said we might need to hire more people for Q4.",
    "Is {wrong_name} joining from home? {other_name} is in the office today and we can meet in person.",
    "I'll check {wrong_name}'s calendar. {other_name} is also free on Tuesday afternoon for a brainstorming session.",
    "{wrong_name} is finishing the design specs. {other_name} will start the implementation phase next week.",
    "Did {wrong_name} see the sales figures? {other_name} was quite impressed by the growth in the EMEA region.",
    "I'll make sure {wrong_name} has access. {other_name} will set up the account permissions for the new tool.",
    "Can {wrong_name} walk us through the journey? {other_name} has some questions about the user checkout flow.",
    "I'll be syncing with {wrong_name}. {other_name} will join us once a week for the high-level status update.",
    "{wrong_name} is our point of contact for HR. {other_name} handles the benefits, payroll, and equity questions.",
    "Did {wrong_name} catch the staging bug? {other_name} is working on a reproduction case in the local environment.",
    "I'll get {wrong_name}'s signature. {other_name} has already signed the document and sent it back to legal.",
    "Is {wrong_name} leading the strategy? {other_name} and {another_name} will be participating as key contributors.",
    "I'll check with {wrong_name} about lunch. {other_name} has a few dietary restrictions we need to consider.",
    "{wrong_name} is our senior-most developer. {other_name} has been with the company for five years now.",
    "Did {wrong_name} mention the requirement? {other_name} is looking into the technical feasibility of the request.",
    "I'll talk to {wrong_name} about the layout. {other_name} has some ideas for the new lounge and coffee area.",
    "Can {wrong_name} help troubleshooting? {other_name} said it might be a DNS issue or a firewall problem.",
    "I'll be presenting with {wrong_name}. {other_name} will be providing technical support during the demo.",
    "{wrong_name} is writing the tutorial script. {other_name} is recording the voiceover in the studio.",
    "Did {wrong_name} approve the request? {other_name} is waiting for the flight confirmation from the agency.",
    "I'll sync with {wrong_name} on the vision. {other_name} is already working on the roadmap for next year.",
    "Is {wrong_name} available for review? {other_name} is currently busy with a critical production bug fix.",
    "I'll check with {wrong_name} about the code. {other_name} said it was business casual for the event tonight.",
    "{wrong_name} is our lead data scientist. {other_name} handles the data engineering and pipeline maintenance.",
    "Did {wrong_name} mention the team meeting? {other_name} said it was mandatory for everyone in the department.",
    "I'll talk to {wrong_name} about mentorship. {other_name} is looking for a new mentor for their career path.",
    "Can {wrong_name} help me with the env? {other_name} suggested using Docker to simplify the setup process.",
    "I'll be working with {wrong_name}. {other_name} is focusing on the frontend mobile app for iOS and Android.",
    "{wrong_name} is coordinating the relocation. {other_name} is managing the equipment inventory and logistics.",
    "Did {wrong_name} approve the license? {other_name} needs it for the new project starting next month.",
    "I'll talk to {wrong_name} about the plan. {other_name} has already had their mid-year review with HR.",
    "Is {wrong_name} joining for dinner? {other_name} and {another_name} are already confirmed for the 7 PM table.",
    "I'll check {wrong_name}'s availability. {other_name} suggested a time on Friday morning for the final demo.",
    "{wrong_name} is drafting the statement. {other_name} is helping with the core values and mission section.",
    "Did {wrong_name} see the guidelines? {other_name} is already updating the website icons and brand colors.",
    "I'll talk to {wrong_name} about the initiative. {other_name} is very passionate about the diversity project.",
    "Can {wrong_name} help with the report? {other_name} showed me the new expense portal yesterday morning.",
    "I'll be collaborating on the API. {other_name} will be testing the endpoints for performance and security.",
    "{wrong_name} is leading the documentation. {other_name} is reviewing the tutorials for clarity and completeness.",
    "Did {wrong_name} catch the sheet error? {other_name} noticed it while checking the totals for the Q2 report.",
    "I'll check with {wrong_name} about the schedule. {other_name} thought the office was closed this coming Friday.",
    "Is {wrong_name} attending the training? {other_name} and {another_name} are already there in the auditorium.",
    "I'll make sure {wrong_name} has the link. {other_name} will be joining the Zoom call from the conference room.",
    "{wrong_name} is our PM for this sprint. {other_name} will take over the planning for the next three weeks.",
]


def generate_examples(num_per_pair=2):
    examples = []
    
    for correct_first, wrong_list in NAME_VARIATIONS:
        for wrong_name in wrong_list:
            if correct_first == wrong_name: continue
            
            # Forward: Correct to match context
            for _ in range(num_per_pair):
                last_name = random.choice(LAST_NAMES)
                template = random.choice(TEMPLATES)
                
                # Create a meeting context with names
                # Ensure we have enough names if the template has {other_name} or {another_name}
                context_size = random.randint(3, 6) # Increased minimum to ensure we have enough for multi-name templates
                context_names = [f"{correct_first} {last_name}"]
                while len(context_names) < context_size:
                    other_first = random.choice(NAME_VARIATIONS)[0]
                    other_last = random.choice(LAST_NAMES)
                    other_full = f"{other_first} {other_last}"
                    if other_full not in context_names:
                        context_names.append(other_full)
                
                random.shuffle(context_names)
                
                # Extract first names for the template (excluding the target correct_first)
                other_first_names = [n.split(' ')[0] for n in context_names if n.split(' ')[0] != correct_first]
                
                fillers = {
                    "wrong_name": wrong_name,
                    "other_name": other_first_names[0] if len(other_first_names) > 0 else "someone",
                    "another_name": other_first_names[1] if len(other_first_names) > 1 else "someone else"
                }
                
                try:
                    raw_phrase = template.format(**fillers)
                    
                    # For corrected_phrase, use the correct version of the target name
                    fillers["wrong_name"] = correct_first
                    corrected_phrase = template.format(**fillers)
                    
                    examples.append({
                        'names': context_names,
                        'raw_phrase': raw_phrase,
                        'corrected_phrase': corrected_phrase
                    })
                except KeyError:
                    # Fallback for templates that might have unexpected placeholders
                    raw_phrase = template.format(wrong_name=wrong_name)
                    corrected_phrase = template.format(wrong_name=correct_first)
                    examples.append({
                        'names': context_names,
                        'raw_phrase': raw_phrase,
                        'corrected_phrase': corrected_phrase
                    })
                
            # Reverse: The raw phrase has the correct spelling but context has the alternative
            last_name = random.choice(LAST_NAMES)
            full_name_alt = f"{wrong_name} {last_name}"
            # For reverse, we keep context simple to focus on the flip
            examples.append({
                'names': [full_name_alt],
                'raw_phrase': f"Hey {correct_first}, can you check the logs?",
                'corrected_phrase': f"Hey {wrong_name}, can you check the logs?"
            })
            
            # Possessive Variant
            last_name = random.choice(LAST_NAMES)
            full_name = f"{correct_first} {last_name}"
            examples.append({
                'names': [full_name],
                'raw_phrase': f"I'm looking at {wrong_name}'s latest update.",
                'corrected_phrase': f"I'm looking at {correct_first}'s latest update."
            })

    return examples

if __name__ == "__main__":
    generated = generate_examples(num_per_pair=5) # Increased number per pair
    print(f"Generated {len(generated)} regular name examples.")
    
    with open("generated_names.jsonl", "w") as f:
        for ex in generated:
            f.write(json.dumps(ex) + "\n")
            
    print("Samples saved to generated_names.jsonl")
    
    # Print a few for verification
    for ex in generated[:5]:
        print(json.dumps(ex, indent=4))
